# Generated by Django 4.1.3 on 2022-12-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Balance'),
        ),
    ]
